# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build_mycp:
  tags:
    - ugrad
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - if [ -f CMakeLists.txt ]; then cmake CMakeLists.txt; fi
    - make
  artifacts:
    paths:
      - mycp/mycp

build_jumpy:
  tags:
    - ugrad
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - if [ -f CMakeLists.txt ]; then cmake CMakeLists.txt; fi
    - make
  artifacts:
    paths:
      - jumpy/jumpy

mycp_00:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 00 . mycp

mycp_01:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 01 . mycp

mycp_02:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 02 . mycp

mycp_03:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 03 . mycp

mycp_04:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 04 . mycp

mycp_05:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 05 . mycp

mycp_06:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 06 . mycp

mycp_07:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 07 . mycp

mycp_08:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 08 . mycp

mycp_09:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd mycp
    - ./tests/test.sh 09 . mycp

jumpy_00:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 00 . jumpy

jumpy_01:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 01 . jumpy

jumpy_02:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 02 . jumpy

jumpy_03:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 03 . jumpy

jumpy_04:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 04 . jumpy

jumpy_05:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 05 . jumpy

jumpy_06:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 06 . jumpy

jumpy_07:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 07 . jumpy

jumpy_08:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 08 . jumpy

jumpy_09:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /NOTEST/
  script:
    - cd jumpy
    - ./tests/test.sh 09 . jumpy
