# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  tags:
    - ugrad
  stage: build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - if [ -f CMakeLists.txt ]; then cmake CMakeLists.txt; fi
    - make
    - cd ..
    - cd problem2
    - if [ -f CMakeLists.txt ]; then cmake CMakeLists.txt; fi
    - make
  artifacts:
    paths:
      - problem1/problem1
      - problem2/problem2

test00:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - ./tests/test.sh 00 . problem1

test01:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - ./tests/test.sh 01 . problem1

test02:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - ./tests/test.sh 02 . problem1

test03:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - ./tests/test.sh 03 . problem1

test04:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem1
    - ./tests/test.sh 04 . problem1

test05:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem2
    - ./tests/test.sh 05 . problem2

test06:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem2
    - ./tests/test.sh 06 . problem2

test07:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem2
    - ./tests/test.sh 07 . problem2

test08:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem2
    - ./tests/test.sh 08 . problem2

test09:
  tags:
    - ugrad
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /release-3145/
  script:
    - cd problem2
    - ./tests/test.sh 09 . problem2
